#!/bin/bash
# /etc/init.d/projector

### BEGIN INIT INFO
# Provides:          projector
# Required-Start:	$network
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       This service is used to manage gtdmobile
### END INIT INFO

case "$1" in
	start)
                sudo node /opt/screen_folding/projector/app.js > log.txt 2>&1 &
		;;
	stop)
		sudo killall node
		;;
	*)
		exit 1
		;;
esac

exit 0
